/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sumit kumar
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    DefaultTableModel model;
    public EditCourse() {
        initComponents();
        setRecordTotable();
    }

    
    public void setRecordTotable(){
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from course");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                
                String courseId = rs.getString("id");
                String courseName = rs.getString("cname");
                String coursePrice = rs.getString("cost");
                
                
                Object[] obj={courseId,courseName,coursePrice};
                model = (DefaultTableModel)tbl_coursedata.getModel();
                model.addRow(obj);
            }   
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void addCourse(int id, String cname, double cost){
          
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("insert into course values(?,?,?)");
            
            pst.setInt(1,id);
            pst.setString(2,cname);
            pst.setDouble(3,cost);
            
            int rowCount = pst.executeUpdate();
            if (rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course Added Sussesfully");
                clearTable();
                setRecordTotable();
            }else{
                JOptionPane.showMessageDialog(this, "Course Insertion Failed");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course Insertion Failed");
            e.printStackTrace();
        }
    }
    
    public void update(int id, String cname, double cost){
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("update course set cname =?,cost =? where id = ?");
            
            pst.setString(1,cname);
            pst.setDouble(2,cost);
            pst.setInt(3,id);
            
            int rowCount = pst.executeUpdate();
            if (rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course Updated Sussesfully");
                clearTable();
                setRecordTotable();
            }else{
                JOptionPane.showMessageDialog(this, "Course Updation Failed");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course Updation Failed");
            e.printStackTrace();
        }
    }
    
        public void Delete(int id){
        
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("delete from course where id = ?");
            
            pst.setInt(1,id);
            
            int rowCount = pst.executeUpdate();
            if (rowCount == 1){
                JOptionPane.showMessageDialog(this, "Course Deleted Sussesfully");
                clearTable();
                setRecordTotable();
            }else{
                JOptionPane.showMessageDialog(this, "Course Deletion Failed");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Course Deletion Failed");
            e.printStackTrace();
        }
    }
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_coursedata.getModel();
        clearTable();
        model.setRowCount(0);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearchrecord = new javax.swing.JPanel();
        btnSearchrecord = new javax.swing.JLabel();
        panelEditcourse = new javax.swing.JPanel();
        btnEditcourse = new javax.swing.JLabel();
        panelCourselist = new javax.swing.JPanel();
        btnCourselist = new javax.swing.JLabel();
        panelViewallrecord = new javax.swing.JPanel();
        btnViewallrecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_coursedata = new javax.swing.JTable();
        txt_courseId = new javax.swing.JTextField();
        txt_courseName = new javax.swing.JTextField();
        txt_coursePrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(204, 204, 255));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(204, 204, 255));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("       Home");
        btnHome.setIconTextGap(5);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsidebar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 360, 70));

        panelSearchrecord.setBackground(new java.awt.Color(204, 204, 255));
        panelSearchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnSearchrecord.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnSearchrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search-user.png"))); // NOI18N
        btnSearchrecord.setText("       Search Record");
        btnSearchrecord.setIconTextGap(5);
        btnSearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSearchrecordLayout = new javax.swing.GroupLayout(panelSearchrecord);
        panelSearchrecord.setLayout(panelSearchrecordLayout);
        panelSearchrecordLayout.setHorizontalGroup(
            panelSearchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchrecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelSearchrecordLayout.setVerticalGroup(
            panelSearchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearchrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsidebar.add(panelSearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 360, 70));

        panelEditcourse.setBackground(new java.awt.Color(204, 204, 255));
        panelEditcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnEditcourse.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnEditcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEditcourse.setText("   Edit Course");
        btnEditcourse.setIconTextGap(5);
        btnEditcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditcourseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditcourseLayout = new javax.swing.GroupLayout(panelEditcourse);
        panelEditcourse.setLayout(panelEditcourseLayout);
        panelEditcourseLayout.setHorizontalGroup(
            panelEditcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditcourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelEditcourseLayout.setVerticalGroup(
            panelEditcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditcourse, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsidebar.add(panelEditcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 360, 70));

        panelCourselist.setBackground(new java.awt.Color(204, 204, 255));
        panelCourselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnCourselist.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnCourselist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list.png"))); // NOI18N
        btnCourselist.setText("       Course List");
        btnCourselist.setIconTextGap(5);
        btnCourselist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourselistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourselistMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCourselistLayout = new javax.swing.GroupLayout(panelCourselist);
        panelCourselist.setLayout(panelCourselistLayout);
        panelCourselistLayout.setHorizontalGroup(
            panelCourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCourselistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCourselist, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCourselistLayout.setVerticalGroup(
            panelCourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCourselistLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCourselist, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelsidebar.add(panelCourselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 360, 70));

        panelViewallrecord.setBackground(new java.awt.Color(204, 204, 255));
        panelViewallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnViewallrecord.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        btnViewallrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view report2.png"))); // NOI18N
        btnViewallrecord.setText("View All Record");
        btnViewallrecord.setIconTextGap(5);
        btnViewallrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewallrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewallrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelViewallrecordLayout = new javax.swing.GroupLayout(panelViewallrecord);
        panelViewallrecord.setLayout(panelViewallrecordLayout);
        panelViewallrecordLayout.setHorizontalGroup(
            panelViewallrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewallrecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewallrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelViewallrecordLayout.setVerticalGroup(
            panelViewallrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewallrecordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewallrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelsidebar.add(panelViewallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 360, 70));

        panelBack.setBackground(new java.awt.Color(204, 204, 255));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btnBack.setText("       Back");
        btnBack.setIconTextGap(5);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsidebar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 770, 360, 70));

        panelLogout.setBackground(new java.awt.Color(204, 204, 255));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255), java.awt.Color.black, java.awt.Color.darkGray, null));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText("       Logout");
        btnLogout.setIconTextGap(5);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoutLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsidebar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 900, 360, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 560, 1100));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_coursedata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbl_coursedata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Course Price"
            }
        ));
        tbl_coursedata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_coursedataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_coursedata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        txt_courseId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt_courseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 310, 50));

        txt_courseName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 310, 50));

        txt_coursePrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txt_coursePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 310, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Course ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 120, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel2.setText("Course Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 140, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText("Course Price :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 140, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 110, 50));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 110, 50));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 110, 50));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Edit Course Detalis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 360, 90));

        jSeparator1.setForeground(new java.awt.Color(255, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 400, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 1100));

        setSize(new java.awt.Dimension(1889, 1148));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchrecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchrecordMouseEntered

    private void btnSearchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchrecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelSearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchrecordMouseExited

    private void btnEditcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditcourseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_btnEditcourseMouseEntered

    private void btnEditcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditcourseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelEditcourse.setBackground(clr);
    }//GEN-LAST:event_btnEditcourseMouseExited

    private void btnCourselistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourselistMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelCourselist.setBackground(clr);
    }//GEN-LAST:event_btnCourselistMouseEntered

    private void btnCourselistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourselistMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelCourselist.setBackground(clr);
    }//GEN-LAST:event_btnCourselistMouseExited

    private void btnViewallrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewallrecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelViewallrecord.setBackground(clr);
    }//GEN-LAST:event_btnViewallrecordMouseEntered

    private void btnViewallrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewallrecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelViewallrecord.setBackground(clr);
    }//GEN-LAST:event_btnViewallrecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 153, 255);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        Color clr = new Color(204, 204, 255);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        home homepage = new home();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int id = Integer.parseInt(txt_courseId.getText());
        String cname = txt_courseName.getText();
        double cost = Double.parseDouble(txt_coursePrice.getText());
        addCourse(id,cname,cost);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_coursedataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_coursedataMouseClicked
        
        int rowNo = tbl_coursedata.getSelectedRow();
        TableModel model = tbl_coursedata.getModel();
        
        txt_courseId.setText(model.getValueAt(rowNo, 0).toString());
        txt_courseName.setText((String)model.getValueAt(rowNo, 1));
        txt_coursePrice.setText(model.getValueAt(rowNo, 2).toString());
         
    }//GEN-LAST:event_tbl_coursedataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int id = Integer.parseInt(txt_courseId.getText());
        String cname = txt_courseName.getText();
        double cost = Double.parseDouble(txt_coursePrice.getText());
        
        update(id,cname,cost);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id = Integer.parseInt(txt_courseId.getText());
        
        Delete(id);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        home homepage = new home();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourselist;
    private javax.swing.JLabel btnEditcourse;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearchrecord;
    private javax.swing.JLabel btnViewallrecord;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourselist;
    private javax.swing.JPanel panelEditcourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSearchrecord;
    private javax.swing.JPanel panelViewallrecord;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JTable tbl_coursedata;
    private javax.swing.JTextField txt_courseId;
    private javax.swing.JTextField txt_courseName;
    private javax.swing.JTextField txt_coursePrice;
    // End of variables declaration//GEN-END:variables
}
